server:
  port: 9000

spring:
  application:
    name: bootcamp-framework-auth
  threads:
    virtual:
      enabled: true
  config:
    import:
      - optional:nacos:bootcamp-framework-auth.yml?group=BOOTCAMP&refreshEnabled=true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: <auth-nacos-namespace-uuid>
        group: BOOTCAMP
      config:
        namespace: <auth-nacos-namespace-uuid>
        group: BOOTCAMP
        file-extension: yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,shutdown,prometheus,metrics"
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  metrics:
    tags:
      application: ${spring.application.name}
